""" Add vault_balance

Revision ID: 76a9bbce2b59
Revises: 539405630c6d
Create Date: 2026-06-30 21:12:54.626998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a9bbce2b59'
down_revision: Union[str, None] = '539405630c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vault_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vault_balance')
    # ### end Alembic commands ###
